language: node_js
node_js:
- 11
dist: trusty
sudo: false
addons:
  ssh_known_hosts:
  - marvin.mannhardt.net
before_install:
- openssl aes-256-cbc -K $encrypted_a626a3773fce_key -iv $encrypted_a626a3773fce_iv
  -in scripts/gatsby-deploy.enc -out /tmp/gatsby-deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/gatsby-deploy
- ssh-add /tmp/gatsby-deploy
- echo -e "Host hwmails.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master
